name: IBM Cloud Auto Restart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 15 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install IBM CLI
      run: curl -sL https://ibm.biz/idt-installer | bash
      
    - name: Login IBM Cloud
      run: |
g    - name: Restart
      run: |
        ibmcloud target -g Default
        ibmcloud target --cf
        ibmcloud cf install
        ibmcloud cf restart ${{ secrets.CFNAME }}
